///////////////////////////////////////////////////////////
//  Receiver.cs
//  Implementation of the Class Receiver
//  Generated by Enterprise Architect
//  Created on:      18-Jan-2022 11:15:09 PM
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Common.Patterns {
	/// <summary>
	/// This class knows how to perform the operations associated with carrying out a
	/// request.
	/// </summary>
	public class Budget {
		private double budget;
		private string house;
		public Budget(double budget, string house){
			this.budget = budget;
			this.house = house;
		}
		public double Action(double amount, Command command){
			if(command is UseBudgetCommand)
			{
				return budget -= amount;
            }
            else
			{
				return budget += amount;
			}
		}

	}//end Receiver

}//end namespace Patterns