///////////////////////////////////////////////////////////
//  Command.cs
//  Implementation of the Class Command
//  Generated by Enterprise Architect
//  Created on:      18-Jan-2022 11:15:08 PM
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Common.Patterns;
namespace Common.Patterns {
	/// <summary>
	/// This class declares an interface for executing an operation.
	/// </summary>
	public abstract class Command
	{
		protected double amount;
		public Budget Budget { get => budget; }
		public double Amount { get => amount; }

		protected Patterns.Budget budget;
		public Command(){

		}

		~Command(){

		}

		/// 
		/// <param name="receiver"></param>
		public Command(Budget budget){

			this.budget = budget;
		}

		public abstract double Execute();

		public abstract double Unexecute();

	}//end Command

}//end namespace Patterns