///////////////////////////////////////////////////////////
//  GetSalaryCommand.cs
//  Implementation of the Class GetSalaryCommand
//  Generated by Enterprise Architect
//  Created on:      18-Jan-2022 11:15:09 PM
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Common.Patterns;
namespace Common.Patterns
{
	/// <summary>
	/// This class (a) defines a binding between a Receiver object and an action, and
	/// (b) implements Execute by invoking the corresponding operation(s) on Receiver.
	/// </summary>
	public class GetSalaryCommand : Command
	{

		/// 
		/// <param name="receiver"></param>
		public GetSalaryCommand(Budget receiver, double amount)
		{
			this.amount = amount;
			this.budget = receiver;
		}
		public override double Execute()
		{
			return budget.Action(amount, this);
		}

		public override double Unexecute()
		{
			return budget.Action(-1 * amount, this);
		}

	}//end GetSalaryCommand

}//end namespace Patterns