///////////////////////////////////////////////////////////
//  NetPositiveState.cs
//  Implementation of the Class NetPositiveState
//  Generated by Enterprise Architect
//  Created on:      18-Jan-2022 11:15:09 PM
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Common.Patterns;
namespace Common.Patterns {
	/// <summary>
	/// This subclass implements a behaviour associated with a state of the Context.
	/// </summary>
	public class NetPositiveState : State {

		public NetPositiveState(){

		}

		~NetPositiveState(){

		}

		/// 
		/// <param name="context"></param>
		public override void Handle(InvokerSubjectContext context){
			context.State = new NetNegativeState();
			context.Notify();
		}

	}//end NetPositiveState

}//end namespace Patterns