///////////////////////////////////////////////////////////
//  Observer.cs
//  Implementation of the Class Observer
//  Generated by Enterprise Architect
//  Created on:      18-Jan-2022 11:15:09 PM
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Common.Patterns {
	/// <summary>
	/// This class defines an updating interface for objects that should be notified of
	/// changes in a subject.
	/// </summary>
	public abstract class Observer {

		public Observer(){

		}

		~Observer(){

		}

		public abstract void Update();

	}//end Observer

}//end namespace Patterns