///////////////////////////////////////////////////////////
//  State.cs
//  Implementation of the Class State
//  Generated by Enterprise Architect
//  Created on:      18-Jan-2022 11:15:09 PM
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Common.Patterns {
	/// <summary>
	/// This class defines an interface for encapsulating the behaviour associated with
	/// a particular state of the Context.
	/// </summary>
	public abstract class State {

		public State(){

		}

		~State(){

		}

		/// 
		/// <param name="context"></param>
		public abstract void Handle(InvokerSubjectContext context);

	}//end State

}//end namespace Patterns