///////////////////////////////////////////////////////////
//  Subject.cs
//  Implementation of the Class Subject
//  Generated by Enterprise Architect
//  Created on:      18-Jan-2022 11:15:09 PM
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Common.Patterns;
namespace Common.Patterns {
	/// <summary>
	/// This class knows its observers and provides an interface for attaching and
	/// detaching Observer objects.
	/// </summary>
	public abstract class Subject {

		public Subject(){

		}

		~Subject(){

		}

		/// 
		/// <param name="observer"></param>
		public abstract void Attach(Observer observer);

		/// 
		/// <param name="observer"></param>
		public abstract void Detach(Observer observer);

		public abstract void Notify();

	}//end Subject

}//end namespace Patterns