///////////////////////////////////////////////////////////
//  Category.cs
//  Implementation of the Class Category
//  Generated by Enterprise Architect
//  Created on:      18-Jan-2022 11:14:22 PM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;
using System.ServiceModel;

namespace Common.HomeBudgetPackage
{
	[DataContract]
	public class Category
	{
		[DataMember]
		public string name;
		[DataMember]
		public Entry m_Entry;
		public Category(Entry entry, string name)
		{
			m_Entry = entry;
			this.name = name;
		}
		public double GetAmount()
        {
			return m_Entry.GetValue();
		}
		public string GetName()
		{
			return name;
		}
		~Category()
		{

		}

	}//end Category
}