///////////////////////////////////////////////////////////
//  Entry.cs
//  Implementation of the Class Entry
//  Generated by Enterprise Architect
//  Created on:      18-Jan-2022 11:14:24 PM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

namespace Common.HomeBudgetPackage
{
	[DataContract]
	public class Entry
	{
		[DataMember]
		private string description;
		[DataMember]
		private DateTime timestamp;
		[DataMember]
		public double value;

		public Entry(string description, double value)
		{
			this.description = description;
			this.value = value;
			timestamp = DateTime.Now;
		}
		public double GetValue()
        {
			return value;
        }
		~Entry()
		{

		}

	}//end Entry
}